### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Shinji-ux** [Shinji-ux/protospace-41418#1]
https://protospace-41418.onrender.com/

**Comment by OMG3215** [comment]
@Shinji-ux さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
